version: "3.8"

services:
  # app:
  #   build: .
  #   container_name: php-todo-app
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./php-todo/:/var/www/html
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=3307
  #     - DB_DATABASE=todo
  #     - DB_USERNAME=todo
  #     - DB_PASSWORD=secret
  db:
    image: arm64v8/mysql:8
    container_name: php-todo-2-db
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todo
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=secret
      - MYSQL_TCP_PORT=3307

volumes:
  db_data:
